Solves a gettext dependency problem for libbfd.a on at least OSX Mountain Lion
GCC compilation fails because libbfd.a is not correctly linked to
gettext. The error is:

http://gcc.gnu.org/wiki/FAQ#Configuration_fails_with_.27.27configure:_error:_cannot_compute_suffix_of_object_files:_cannot_compile.27.27._What_is_the_problem.3F

And occurrs because the binutil tools fail with something like:
collect2: ld terminated with signal 5 [Trace/BPT trap]
dyld: lazy symbol binding failed: Symbol not found: _libintl_dgettext
  Referenced from: /Volumes/btc-
0.12/gcc-4.4/i386-apple-darwin9.8.0/powerpc-linux-gnu/lib/libb
fd-2.20.1.20100303.dylib
  Expected in: dynamic lookup

I found out that a link from libbfd.a to libintl.a had to be created
under the following url: http://www.telegraphics.com.au/~fthain/sw/build-
tool-chain/btc-20110616/patches/binutils-2.20.1-darwin-libbfd-link.diff

Although the workaround worked for GCC without newlib, it failed with it
because it was generating multiple definitions due to compiling
libintl.a into libbfd.a instead of linking.
Relevant libbfd.a compilation warning:
*** Warning: Linking the shared library libbfd.la against the
*** static library ../intl/libintl.a is not portable!

Giving a try to some reading about autobuild, I have came up with a
patch that worked under both cases (with and without newlib).